# Generated by Django 5.2.8 on 2025-12-11 15:59

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_type', models.CharField(choices=[('presidential', 'Presidential'), ('governorship', 'Governorship'), ('senatorial', 'Senatorial')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('party', models.CharField(max_length=100)),
                ('party_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='party_image')),
                ('age', models.IntegerField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='PartyVoteCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_type', models.CharField(choices=[('presidential', 'Presidential'), ('governorship', 'Governorship'), ('senatorial', 'Senatorial')], max_length=20)),
                ('party', models.CharField(max_length=100)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('party_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='party_image')),
            ],
            options={
                'unique_together': {('election_type', 'party')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_type', models.CharField(editable=False, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.candidate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'election_type'), name='unique_vote_per_election')],
            },
        ),
    ]
