# Generated by Django 5.2.8 on 2025-12-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='election_type',
            field=models.CharField(choices=[('presidential', 'Presidential'), ('governorship', 'Governorship'), ('senatorial', 'Senatorial')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='partyvotecount',
            name='election_type',
            field=models.CharField(choices=[('presidential', 'Presidential'), ('governorship', 'Governorship'), ('senatorial', 'Senatorial')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='partyvotecount',
            name='party',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['election_type', 'party', 'name'], name='vote_candid_electio_80e48e_idx'),
        ),
    ]
